### ISSUE TITLE
No file index.html

### ISSUE THREAD

**Issue by hermannw** [WallaceIT/ICDBNavigator#6]
I cloned the git to my Raspberry Pi and run setup.php without problems

"creating data directories...[OK]
writing config.php file...[OK]
creating new database...[OK]
creating data subdirectories...[OK]
creating default packages...
Package files generated for DIP, pin counts: 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 40,
Package files generated for SOIC, pin counts: 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 40,
Package files generated for SSOP, pin counts: 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 40,
Package files generated for QFP, pin counts: 28, 32, 40, 44, 64, 80, 100,
Package files generated for TO92, pin counts: 3,
Package files generated for TO220, pin counts: 3, 5, 7, 15, 20,
Package files generated for SOT23, pin counts: 3, 5, 6
Package file generated for OTHER
[OK]
ICDBNavigator Installed!
(Please remove this file...)

Go to ICDBN Homepage"

When I click on "Go to ICDBN Homepage" it directs me to 192.168.1.120/icdbn/index.html but this file does not exist. Am I missing something?

**Comment by WallaceIT** [comment]
Hi, sorry for the long wait but I've had some personal problems that distracted me from the repo.
The last commit should fix your issues.
Thanks for the feedback and please forgive me.
